server:
  port: 81

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.16.169:3306/luntan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.163.com
    username: bonelysjj@163.com
    password: SQYJNMSINYEIIFKS
    port: 25
    properties:
      mail:
        smtl:
          auth: true
        smtp:
          starttls:
            enable: true
            required: true

#mybatisplus相关配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


#自定义
community:
  path:
    domain: http://localhost:81